SCREENWIDTH = 720
SCREENHEIGHT = 540

LOCALDIR = "/home/pi/OutsideTheBox/X/PiDev/"

STDOUTFILE = LOCALDIR + "console_output.txt"
XSMARTLOG = LOCALDIR + "xsmart_log.txt"
STDOUTVIAFILE = 1
STDOUTVIACONS = 2
STDOUT = STDOUTVIAFILE

DATA = LOCALDIR + "data/"
VIDEOS = DATA + "videos/"
PICS = DATA + "storypics/"

VIDEOMODE = 1
STORYMODE = 2

MODEBUTTON = 17
ADVANCEBUTTON = 22

FONT = LOCALDIR + "AblePro.otf"
BLUE = (15, 128, 191)
ORANGE = (238,127,0)
BACKGROUNDCOLOUR = (250, 250, 250)

WAITCTR = 5
MAXPICS = 10
MAXVIDS = 3

FPS = 60

LOGON = False
